### ISSUE TITLE
Invalid xml due to invalid tag names

### ISSUE THREAD

**Issue by panicbit** [alexislours/msbt#1]
Tags starting with digits like `<10_10 />` are invalid xml and are rejected by some parsers.

Example:
https://github.com/alexislours/msbt/blob/eab3442f49199c3058082f0d7ee62516fc95ff12/TalkSNpc_EUen/owl/SP_owl_Comment_Fish.xml#L17

**Comment by alexislours** [comment]
Open an issue on https://github.com/Treeki/CylindricalEarth, this is outside the scope of this repo.
